### ISSUE TITLE
Support for SNMPv1

### ISSUE THREAD

**Issue by Chaz6** [fboaventura/dckr-mrtg#2] opened 2021-06-03 08:28 UTC
I would like to use dckr-mrtg with a HP LaserJet P2015 printer which requires SNMPv1. When I try to add the device, it reports `Timeout: No Response from [host]`.

**Comment by fboaventura** [comment] 2021-06-03 12:40
Let me see what I can do :)

**Comment by fboaventura** [comment] 2021-06-07 00:19
Hi @Chaz6!

Can you, please, give a run to `fboaventura/dckr-mrtg:mrtg-rrd` and see if it will work for you?

I was already working on a change, to implement `rrdtool` so I sized the opportunity to make it live.  Please, read the [README.md](https://github.com/fboaventura/dckr-mrtg/blob/mrtg-rrd/README.md) and verify the changes, if there is anything that you may have to change on your side.

If everything works on your side, I'll merge into `master` and make a proper release.

Thanks!

**Comment by Chaz6** [comment] 2021-06-08 12:11
Thanks! I will give it a try this afternoon.

**Comment by Chaz6** [comment] 2021-06-08 12:25
The device picked up correctly, but it did not show up on the main page.

```
mrtg_1  | --base: Get Device Info on public@PRINTER:::::1
mrtg_1  | --base: Vendor Id: hp
mrtg_1  | --base: Populating confcache
mrtg_1  | --base: Get Interface Info
mrtg_1  | --base: Walking ifIndex
mrtg_1  | --snpd:   public@PRINTER:::::1 -> 1 -> ifIndex = 1
mrtg_1  | --snpd:   public@PRINTER:::::1 -> 2 -> ifIndex = 2
mrtg_1  | --base: Walking ifType
mrtg_1  | --snpd:   public@PRINTER:::::1 -> 1 -> ifType = 24
mrtg_1  | --snpd:   public@PRINTER:::::1 -> 2 -> ifType = 6
mrtg_1  | --base: Walking ifAdminStatus
mrtg_1  | --snpd:   public@PRINTER:::::1 -> 1 -> ifAdminStatus = 1
mrtg_1  | --snpd:   public@PRINTER:::::1 -> 2 -> ifAdminStatus = 1
mrtg_1  | --base: Walking ifOperStatus
mrtg_1  | --snpd:   public@PRINTER:::::1 -> 1 -> ifOperStatus = 1
mrtg_1  | --snpd:   public@PRINTER:::::1 -> 2 -> ifOperStatus = 1
mrtg_1  | --base: Walking ifMtu
mrtg_1  | --snpd:   public@PRINTER:::::1 -> 1 -> ifMtu = 1500
mrtg_1  | --snpd:   public@PRINTER:::::1 -> 2 -> ifMtu = 1500
mrtg_1  | --base: Walking ifAlias
mrtg_1  | --base: Walking ifSpeed
mrtg_1  | --snpd:   public@PRINTER:::::1 -> 1 -> ifSpeed = 0
mrtg_1  | --snpd:   public@PRINTER:::::1 -> 2 -> ifSpeed = 10000000
mrtg_1  | --base: Writing /etc/mrtg/conf.d/PRINTER.cfg
```

I also noticed there appears to be a bit of corruption in the charts:-

![image](https://user-images.githubusercontent.com/12680/121184305-df125880-c85c-11eb-9d6d-3f4554a84bbb.png)

Finally, some resources seem to be missing:-

![image](https://user-images.githubusercontent.com/12680/121184386-f2252880-c85c-11eb-97f3-42b5f1744891.png)

**Comment by fboaventura** [comment] 2021-06-08 18:07
Hi @Chaz6!

I couldn't reproduce the missing graphic on the main page.  I've only seen this on my first run of this instance, before the first MRTG execution.  But if you are mounting the volumes for persistency, please, make sure that you are pointing the volumes to the right place:

```yaml
    volumes:
      - "./conf.d:/etc/mrtg/conf.d"
      - "./html:/mrtg/html"
```

As for the graphic corruption, here they are showing like this, with the `nan` before it pools the devices for the second time and has actual data do plot:

![Screenshot_20210608_145427](https://user-images.githubusercontent.com/54273/121234648-54385a80-c86a-11eb-89c1-4959a8376747.png)

After the second pooling, everything gets back to normal:

![Screenshot_20210608_145039](https://user-images.githubusercontent.com/54273/121234840-8944ad00-c86a-11eb-979e-60166d707ff0.png)

I've fixed the missing resources and changed the graphic font to something more readable.

**Comment by fboaventura** [comment] 2021-06-10 19:40
@Chaz6 did you have the opportunity to validate?  Can I close the issue? :)

**Closed as completed** 2021-06-11 12:18 UTC
Labels: enhancement
